#!/usr/bin/env bash

echo "[LINUX ENVIRONMENT] Start the setup"
echo "Debian distribution (Ubuntu)"

echo "--------------------------------------------"
echo "[ACTION] List the shells available"
# sudo cat /etc/shells # - UNCOMMENT
echo "--------------------------------------------"

echo "[ACTION] Define the path to the bash shell"
# chsh -s $(which bash) # - UNCOMMENT
echo "--------------------------------------------"

echo "[ACTION] Update the repositories"
# sudo apt update - UNCOMMENT
echo "--------------------------------------------"

echo "[ACTION] Upgrade the repositories"
# sudo apt upgrade - UNCOMMENT
echo "--------------------------------------------"


echo "[ACTION] Install dependencies"
echo "[LIST] cURL, wget, tmux, git, dconf-cli, uuid-runtime"
# Gogh dependencies - dconf-cli, uuid-runtime
sudo apt install \
	curl \
	tmux \
	wget \
	git \
	dconf-cli \
	uuid-runtime
echo "--------------------------------------------"

echo "[ACTION] Create Gnome Terminal profile with the name 'Default'"
# [TODO] Stop the script OR create the command to do that automatically

# Put this into a README.md
# Gogh can have an issue with Gnome Profile, while installing
# the color schemas. Please, visit this link: https://github.com/Mayccoll/Gogh/issues/203
echo "--------------------------------------------"

echo "[ACTION] Install ZSH and make it a default shell"
# Need to have if/else statements to chech if zsh is installed
# and if it is a default shell
# sudo apt install zsh # - UNCOMMENT
# zsh --version # - UNCOMMENT
# chsh -s $(which zsh) # - UNCOMMENT
echo "[ACTION] ZSH was defined as a default shell"
echo "--- Please, log out and log in back to check if everything is okay"
echo "--- Use 'echo $SHELL' OR '$SHELL --version' command to check the result (/bin/zsh)"
echo "--------------------------------------------"

echo "[ACTION] Install Oh My ZSH"
# sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" # - UNCOMMENT
echo "--------------------------------------------"

echo "[ACTION] Install Color scheme for your terminal (Gogh)"
# Color scheme for your terminal
# https://github.com/Mayccoll/Gogh

# zsh -c "$(wget -qO- https://git.io/vQgMr)" # - UNCOMMENT

# MANUAL MODE

# clone the repo into "$HOME/src/gogh"
# mkdir -p "$HOME/ubuntu-env" # - UNCOMMENT
# cd "$HOME/ubuntu-env" # - UNCOMMENT
# git clone https://github.com/Mayccoll/Gogh.git gogh # - UNCOMMENT
# cd gogh/themes # - UNCOMMENT

# necessary on ubuntu
# export TERMINAL=gnome-terminal # - UNCOMMENT

# install themes
# ./atom.sh # - UNCOMMENT
# ./dracula.sh # - UNCOMMENT
# ./material.sh # - UNCOMMENT
# ./molokai.sh # - UNCOMMENT

# Put this into a README.md
# Gogh can have an issue with Gnome Profile, while installing
# the color schemas. Please, visit this link: https://github.com/Mayccoll/Gogh/issues/203

# [TODO] Specify theme / profile to apply with the command
echo "--------------------------------------------"


echo "[ACTION] Copy the TMUX Configuration file into the $HOME directory"
cp .tmux.conf "$HOME/.tmux.conf"
echo "--------------------------------------------"

echo "[ACTION] Copy the VIM configuration and install plugins"
# [TODO] Remove outdated packages
echo "--------------------------------------------"

echo "[ACTION] Remove outdated packages"
# [TODO] Remove outdated packages
# Autoremove outdated dependencies
# sudo apt autoremove
echo "--------------------------------------------"
