#!/usr/bin/env bash

echo "[LINUX ENVIRONMENT] Start the setup"
echo "Debian distribution (Ubuntu)"

echo "--------------------------------------------"
echo "[ACTION] List the shells available"
# sudo cat /etc/shells # - UNCOMMENT
echo "--------------------------------------------"

echo "[ACTION] Define the path to the bash shell"
# chsh -s $(which bash) # - UNCOMMENT
echo "--------------------------------------------"

echo "[ACTION] Update the repositories"
# sudo apt update # - UNCOMMENT
echo "--------------------------------------------"

echo "[ACTION] Upgrade the repositories"
# sudo apt upgrade # - UNCOMMENT
echo "--------------------------------------------"


echo "[ACTION] Install dependencies"
echo "[LIST] cURL, wget, tmux, git, dconf-cli, uuid-runtime"
# Gogh dependencies - dconf-cli, uuid-runtime
# sudo apt install \
# 	curl \
# 	tmux \
# 	wget \
# 	git \
# 	dconf-cli \
# 	uuid-runtime
echo "--------------------------------------------"

echo "[ACTION] Create Gnome Terminal profile with the name 'Default'"
# [TODO] Stop the script OR create the command to do that automatically

# Put this into a README.md
# Gogh can have an issue with Gnome Profile, while installing
# the color schemas. Please, visit this link: https://github.com/Mayccoll/Gogh/issues/203
echo "--------------------------------------------"

echo "[ACTION] Install ZSH and make it a default shell"
# Need to have if/else statements to chech if zsh is installed
if [[ ! -n "$($SHELL -c 'echo $ZSH_VERSION')" ]];
then
	sudo apt install zsh # - UNCOMMENT
	zsh --version # - UNCOMMENT
	# Do it a default shell
	chsh -s $(which zsh) # - UNCOMMENT

	echo "[FOLLOW ALONG] ZSH was defined as a default shell"
	echo "--- Please, log out and log in back to check if everything is okay"
	echo "--- Use 'echo $SHELL' OR '$SHELL --version' command to check the result (/bin/zsh)"
	echo "--------------------------------------------"
else
	echo "[...no need to act...] zsh is installed"
	echo "--------------------------------------------"
fi

if [ ! -d ~/.oh-my-zsh ];
then
	echo "[ACTION] Install Oh My ZSH"
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" # - UNCOMMENT
	echo "--------------------------------------------"
else
	echo "[...no need to act...] oh-my-zsh is installed"
	echo "--------------------------------------------"
fi

echo "[ACTION] Install Color scheme for your terminal (Gogh)"
echo "--------------------------------------------"
# Color scheme for your terminal
# https://github.com/Mayccoll/Gogh

# zsh -c "$(wget -qO- https://git.io/vQgMr)" # - UNCOMMENT

# MANUAL MODE

# clone the repo into "$HOME/src/gogh"
# mkdir -p "$HOME/ubuntu-env" # - UNCOMMENT
# cd "$HOME/ubuntu-env" # - UNCOMMENT
# git clone https://github.com/Mayccoll/Gogh.git gogh # - UNCOMMENT
# cd gogh/themes # - UNCOMMENT

# necessary on ubuntu
# export TERMINAL=gnome-terminal # - UNCOMMENT

# install themes
# ./atom.sh # - UNCOMMENT
# ./dracula.sh # - UNCOMMENT
# ./material.sh # - UNCOMMENT
# ./molokai.sh # - UNCOMMENT

# Put this into a README.md
# Gogh can have an issue with Gnome Profile, while installing
# the color schemas. Please, visit this link: https://github.com/Mayccoll/Gogh/issues/203

# [TODO] Specify theme / profile to apply with the command

echo ">>> Player TMUX joined the game!"
if [ ! -d ~/.tmux/plugins/tpm ];
then
	echo "[ACTION] Install TMUX Plugin Manager (TPM)"
	git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm
	echo "--------------------------------------------"
else
	echo "[...no need to act...] TMUX Plugin Manager (TPM) is installed"
	echo "--------------------------------------------"
fi

echo "--------------------------------------------"
echo "[ACTION] Copy the TMUX Configuration file into the $HOME directory"
# Don't use $HOME directory for the dot-files. The modern way is to keep everything in $XDG_CONFIG_HOME, which is $HOME/.config/. However, we will use the old way for now.
# cp .tmux.conf "$HOME/.tmux.conf"

echo "--------------------------------------------"

echo "[ACTION] Copy the VIM configuration and install plugins"
# [TODO] Remove outdated packages
echo "--------------------------------------------"

echo "[ACTION] Remove outdated packages"
# [TODO] Remove outdated packages
# Autoremove outdated dependencies
# sudo apt autoremove
echo "--------------------------------------------"
