#!/usr/bin/env bash

./install-deps.sh # UNCOMMENT

echo "--------------------------------------------"

echo "[ACTION] Create Gnome Terminal profile with the name 'Default'"
# [TODO] Stop the script OR create the command to do that automatically

# Put this into a README.md
# Gogh can have an issue with Gnome Profile, while installing
# the color schemas. Please, visit this link: https://github.com/Mayccoll/Gogh/issues/203
echo "--------------------------------------------"

./install-zsh.sh # UNCOMMENT
./install-oh-my-zsh.sh # UNCOMMENT

echo "[ACTION] Install Color scheme for your terminal (Gogh)"
echo "--------------------------------------------"
# Color scheme for your terminal
# https://github.com/Mayccoll/Gogh

# zsh -c "$(wget -qO- https://git.io/vQgMr)" # - UNCOMMENT

# MANUAL MODE

# clone the repo into "$HOME/src/gogh"
# mkdir -p "$HOME/ubuntu-env" # - UNCOMMENT
# cd "$HOME/ubuntu-env" # - UNCOMMENT
# git clone https://github.com/Mayccoll/Gogh.git gogh # - UNCOMMENT
# cd gogh/themes # - UNCOMMENT

# necessary on ubuntu
# export TERMINAL=gnome-terminal # - UNCOMMENT

# install themes
# ./atom.sh # - UNCOMMENT
# ./dracula.sh # - UNCOMMENT
# ./material.sh # - UNCOMMENT
# ./molokai.sh # - UNCOMMENT

# Put this into a README.md
# Gogh can have an issue with Gnome Profile, while installing
# the color schemas. Please, visit this link: https://github.com/Mayccoll/Gogh/issues/203

# [TODO] Specify theme / profile to apply with the command

## IMPORTANT to make a separate script
echo "--------------------------------------------"

# ./install-nvim.sh # UNCOMMENT
# ./install-nvchad-font.sh # UNCOMMENT
# ./install-nvchad.sh # UNCOMMENT

echo "[MANUAL ACTION] Intermediate Stop"
